export const productCategories = [
  "Body Care",
  "Amulets",
  "Cystitis",
  "WhiteHat",
  "Hearing disease",
  "CBD",
  "Cellulite",
  "Cholesterol",
  "Buttocks enlargement",
  "Penis enlargement",
  "Breast enlargement",
  "Testosterone",
  "Joints",
  "Sleep",
  "General health",
  "Rehab",
  "Psoriasis",
  "Acne",
  "Prostatitis",
  "Probiotics",
  "Diet - Weight Loss",
  "Enhancement",
  "Liver",
  "Parasites",
  "Papillomas",
  "Teeth whitening",
  "Pain relief",
  "Mood",
  "Muscle",
  "Wrinkles",
  "Brain",
  "Medical cosmetics",
  "Smoking",
  "Correctors",
  "Immunity",
  "Eyesight",
  "Women's Health",
  "Diabetes",
  "Detox",
  "Depilation",
  "Make-up",
  "Fungus",
  "Hypertension",
  "Haemorrhoids",
  "Gastritis",
  "Hair",
  "Aphrodisiacs",
  "Vitamins",
  "Varicose",
  "Valgus",
  "Beard",
  "No niche",
  "Anti-aging cosmetics",
  "Allergy",
  "Alcoholism",
];
